selfservice:
  methods:
    oidc:
      enabled: true

  flows:
    login:
      ui_url: http://localhost:3000/login
    registration:
      ui_url: http://localhost:3000/register

  # Optional: redirect after login
  after:
    login:
      default_browser_return_url: http://localhost:3000/dashboard

identity:
  default_schema_url: file:///etc/config/identity.schema.json

  schemas:
    - id: default
      url: file:///etc/config/identity.schema.json

oidc:
  config:
    providers:
      - id: google
        provider: google
        client_id: 1054514447528-rnakjmumn1s439bv4c3g85tv9k11viid.apps.googleusercontent.com
        client_secret: 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
        mapper_url: file:///etc/config/oidc.google.mapper.json
        scope:
          - openid
          - email
          - profile
        requested_claims:
          id_token:
            email:
              essential: true
            email_verified:
              essential: true
        # Optional: อนุญาต email domain เฉพาะ
        # allowed_domains:
        #   - example.com
